config/routes.rb
Rails.application.routes.draw do
  resources :paragelia

  resources :pelatis

end

app/models/paragelium.rb
class Paragelium < ActiveRecord::Base
end

app/models/pelati.rb
class Pelati < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paragelia_controller.rb
class ParageliaController < ApplicationController
  before_action :set_paragelium, only: [:show, :edit, :update, :destroy]

  # GET /paragelia
  # GET /paragelia.json
  def index
    @paragelia = Paragelium.all
  end

  # GET /paragelia/1
  # GET /paragelia/1.json
  def show
  end

  # GET /paragelia/new
  def new
    @paragelium = Paragelium.new
  end

  # GET /paragelia/1/edit
  def edit
  end

  # POST /paragelia
  # POST /paragelia.json
  def create
    @paragelium = Paragelium.new(paragelium_params)

    respond_to do |format|
      if @paragelium.save
        format.html { redirect_to @paragelium, notice: 'Paragelium was successfully created.' }
        format.json { render :show, status: :created, location: @paragelium }
      else
        format.html { render :new }
        format.json { render json: @paragelium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paragelia/1
  # PATCH/PUT /paragelia/1.json
  def update
    respond_to do |format|
      if @paragelium.update(paragelium_params)
        format.html { redirect_to @paragelium, notice: 'Paragelium was successfully updated.' }
        format.json { render :show, status: :ok, location: @paragelium }
      else
        format.html { render :edit }
        format.json { render json: @paragelium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paragelia/1
  # DELETE /paragelia/1.json
  def destroy
    @paragelium.destroy
    respond_to do |format|
      format.html { redirect_to paragelia_url, notice: 'Paragelium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paragelium
      @paragelium = Paragelium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paragelium_params
      params.require(:paragelium).permit(:drinks, :food)
    end
end

app/controllers/pelatis_controller.rb
class PelatisController < ApplicationController
  before_action :set_pelati, only: [:show, :edit, :update, :destroy]

  # GET /pelatis
  # GET /pelatis.json
  def index
    @pelatis = Pelati.all
  end

  # GET /pelatis/1
  # GET /pelatis/1.json
  def show
  end

  # GET /pelatis/new
  def new
    @pelati = Pelati.new
  end

  # GET /pelatis/1/edit
  def edit
  end

  # POST /pelatis
  # POST /pelatis.json
  def create
    @pelati = Pelati.new(pelati_params)

    respond_to do |format|
      if @pelati.save
        format.html { redirect_to @pelati, notice: 'Pelati was successfully created.' }
        format.json { render :show, status: :created, location: @pelati }
      else
        format.html { render :new }
        format.json { render json: @pelati.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pelatis/1
  # PATCH/PUT /pelatis/1.json
  def update
    respond_to do |format|
      if @pelati.update(pelati_params)
        format.html { redirect_to @pelati, notice: 'Pelati was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelati }
      else
        format.html { render :edit }
        format.json { render json: @pelati.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pelatis/1
  # DELETE /pelatis/1.json
  def destroy
    @pelati.destroy
    respond_to do |format|
      format.html { redirect_to pelatis_url, notice: 'Pelati was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelati
      @pelati = Pelati.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelati_params
      params.require(:pelati).permit(:onoma, :epitheto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paragelia_helper.rb
module ParageliaHelper
end

app/helpers/pelatis_helper.rb
module PelatisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cafe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paragelia/_form.html.erb
<%= form_for(@paragelium) do |f| %>
  <% if @paragelium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paragelium.errors.count, "error") %> prohibited this paragelium from being saved:</h2>

      <ul>
      <% @paragelium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :drinks %><br>
    <%= f.text_area :drinks %>
  </div>
  <div class="field">
    <%= f.label :food %><br>
    <%= f.text_area :food %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paragelia/edit.html.erb
<h1>Editing paragelium</h1>

<%= render 'form' %>

<%= link_to 'Show', @paragelium %> |
<%= link_to 'Back', paragelia_path %>

app/views/paragelia/index.html.erb
<h1>Listing paragelia</h1>

<table>
  <thead>
    <tr>
      <th>Drinks</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paragelia.each do |paragelium| %>
      <tr>
        <td><%= paragelium.drinks %></td>
        <td><%= paragelium.food %></td>
        <td><%= link_to 'Show', paragelium %></td>
        <td><%= link_to 'Edit', edit_paragelium_path(paragelium) %></td>
        <td><%= link_to 'Destroy', paragelium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paragelium', new_paragelium_path %>

app/views/paragelia/new.html.erb
<h1>New paragelium</h1>

<%= render 'form' %>

<%= link_to 'Back', paragelia_path %>

app/views/paragelia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drinks:</strong>
  <%= @paragelium.drinks %>
</p>

<p>
  <strong>Food:</strong>
  <%= @paragelium.food %>
</p>

<%= link_to 'Edit', edit_paragelium_path(@paragelium) %> |
<%= link_to 'Back', paragelia_path %>

app/views/pelatis/_form.html.erb
<%= form_for(@pelati) do |f| %>
  <% if @pelati.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pelati.errors.count, "error") %> prohibited this pelati from being saved:</h2>

      <ul>
      <% @pelati.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :onoma %><br>
    <%= f.text_field :onoma %>
  </div>
  <div class="field">
    <%= f.label :epitheto %><br>
    <%= f.text_field :epitheto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pelatis/edit.html.erb
<h1>Editing pelati</h1>

<%= render 'form' %>

<%= link_to 'Show', @pelati %> |
<%= link_to 'Back', pelatis_path %>

app/views/pelatis/index.html.erb
<h1>Listing pelatis</h1>

<table>
  <thead>
    <tr>
      <th>Onoma</th>
      <th>Epitheto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pelatis.each do |pelati| %>
      <tr>
        <td><%= pelati.onoma %></td>
        <td><%= pelati.epitheto %></td>
        <td><%= link_to 'Show', pelati %></td>
        <td><%= link_to 'Edit', edit_pelati_path(pelati) %></td>
        <td><%= link_to 'Destroy', pelati, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pelati', new_pelati_path %>

app/views/pelatis/new.html.erb
<h1>New pelati</h1>

<%= render 'form' %>

<%= link_to 'Back', pelatis_path %>

app/views/pelatis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Onoma:</strong>
  <%= @pelati.onoma %>
</p>

<p>
  <strong>Epitheto:</strong>
  <%= @pelati.epitheto %>
</p>

<%= link_to 'Edit', edit_pelati_path(@pelati) %> |
<%= link_to 'Back', pelatis_path %>